services:
  - type: web
    name: gestor-os
    env: python
    buildCommand: >-
      pip install -r requirements.txt &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      python manage.py ensure_superuser
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DJANGO_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_PASSWORD
        value: ADM@123654
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com