# Generated by Django 6.0.2 on 2026-03-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(default='orcamento_global', max_length=50, unique=True)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sequência de oramento',
                'verbose_name_plural': 'Sequências de orçamento',
            },
        ),
    ]
