# Generated by Django 6.0.2 on 2026-02-11 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                (
                    "cod_centro",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "centro_pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcentros",
                        to="cadastro.centrocusto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
                "ordering": ["descricao"],
            },
        ),
    ]
