# Generated by Django 6.0.2 on 2026-02-12 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0007_apontamentohoras_cliente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apontamentohoras",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordens_servic",
                to="cadastro.cliente",
            ),
        ),
    ]
