# Generated by Django 6.0.2 on 2026-02-22 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_apontamentohoras_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao_colab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao da Função')),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Valor_Hora')),
            ],
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='valor_hora',
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='descricao',
            field=models.CharField(max_length=200, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Função_Colaborador', to='cadastro.funcao_colab'),
        ),
    ]
