# Generated by Django 6.0.2 on 2026-04-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_alter_centrocusto_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApontamentoHoras',
        ),
    ]
