# Generated by Django 6.0.2 on 2026-02-12 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastro", "0008_alter_apontamentohoras_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="AberturaOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_os",
                    models.CharField(
                        editable=False,
                        max_length=8,
                        unique=True,
                        verbose_name="Número da OS",
                    ),
                ),
                ("descricao_os", models.TextField(verbose_name="Descrição")),
                ("ssm", models.CharField(max_length=10)),
                (
                    "situacao",
                    models.CharField(
                        choices=[("AB", "Ativa"), ("FI", "Finalizada")],
                        default="AB",
                        max_length=2,
                    ),
                ),
                ("data_abertura", models.DateTimeField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "centro_custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_servico",
                        to="cadastro.centrocusto",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_servico",
                        to="cadastro.cliente",
                    ),
                ),
                (
                    "motivo_intervencao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_servico",
                        to="cadastro.intervencao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
                "ordering": ["-data_abertura"],
                "indexes": [
                    models.Index(
                        fields=["numero_os"], name="abertura_os_numero__13ac7c_idx"
                    ),
                    models.Index(
                        fields=["situacao"], name="abertura_os_situaca_347b28_idx"
                    ),
                ],
            },
        ),
    ]
