# Generated by Django 6.0.2 on 2026-05-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abertura_os', '0002_finalizacaoos_pecaaplicada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aberturaos',
            name='numero_os',
            field=models.CharField(editable=False, max_length=9, unique=True, verbose_name='Número da OS'),
        ),
    ]
