# Generated by Django 6.0.2 on 2026-03-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abertura_os', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizacaoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_tecnica_avaria', models.TextField(verbose_name='Descrição Técnica da Avaria')),
                ('descricao_intervencao', models.TextField(verbose_name='Descrição da Intervenção')),
                ('descricao_sintoma', models.TextField(verbose_name='Descrição do Sintoma')),
                ('causa', models.TextField(verbose_name='Causa')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Data/Hora de Início')),
                ('data_hora_fim', models.DateTimeField(verbose_name='Data/Hora de Fim')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('finalizado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalizacao', to='abertura_os.aberturaos')),
            ],
            options={
                'verbose_name': 'Finalização de OS',
                'verbose_name_plural': 'Finalizações de OS',
                'ordering': ['-finalizado_em'],
            },
        ),
        migrations.CreateModel(
            name='PecaAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('finalizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_aplicadas', to='abertura_os.finalizacaoos')),
            ],
            options={
                'verbose_name': 'Peça Aplicada',
                'verbose_name_plural': 'Peças Aplicadas',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='finalizacaoos',
            index=models.Index(fields=['data_hora_inicio'], name='abertura_os_data_ho_1939a9_idx'),
        ),
        migrations.AddIndex(
            model_name='finalizacaoos',
            index=models.Index(fields=['data_hora_fim'], name='abertura_os_data_ho_c66b9a_idx'),
        ),
    ]
