# Generated by Django 6.0.2 on 2026-02-11 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0002_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="AberturaOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_servico",
                        to="cadastro.cliente",
                    ),
                ),
            ],
        ),
    ]
