# Generated by Django 6.0.2 on 2026-02-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0003_aberturaos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intervencao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo",
                    models.PositiveIntegerField(unique=True, verbose_name="Código"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "Intervenção",
                "verbose_name_plural": "Intervenções",
                "db_table": "intervencao",
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["descricao"], name="intervencao_descric_65f540_idx"
                    )
                ],
            },
        ),
    ]
