# Generated by Django 6.0.2 on 2026-02-11 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0004_intervencao"),
    ]

    operations = [
        migrations.AddField(
            model_name="aberturaos",
            name="intervencao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aberturaos",
                to="cadastro.intervencao",
            ),
            preserve_default=False,
        ),
    ]
