# Generated by Django 6.0.2 on 2026-02-12 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0005_aberturaos_intervencao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=4, unique=True, verbose_name="Matrícula"
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("funcao", models.CharField(max_length=150, verbose_name="Função")),
                (
                    "valor_hora",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=7,
                        verbose_name="Valor Hora",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("A", "A - 07:00 às 11:00 / 12:00 às 16:48"),
                            ("B", "B - 16:48 às 19:00 / 20:00 às 02:00"),
                            ("HC", "H/C - 08:00 às 12:00 / 13:00 às 17:48"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=10,
                        verbose_name="Turno",
                    ),
                ),
                ("hr_entrada_am", models.TimeField(blank=True, null=True)),
                ("hr_saida_am", models.TimeField(blank=True, null=True)),
                ("hr_entrada_pm", models.TimeField(blank=True, null=True)),
                ("hr_saida_pm", models.TimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ApontamentoHoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.colaborador",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AberturaOS",
        ),
    ]
