# Generated by Django 6.0.2 on 2026-02-12 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0006_colaborador_apontamentohoras_delete_aberturaos"),
    ]

    operations = [
        migrations.AddField(
            model_name="apontamentohoras",
            name="cliente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordens_servico",
                to="cadastro.cliente",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apontamentohoras",
            name="intervencao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aberturas",
                to="cadastro.intervencao",
            ),
            preserve_default=False,
        ),
    ]
