# Generated by Django 6.0.2 on 2026-02-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_funcao_colab_remove_colaborador_valor_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao_colab',
            name='descricao',
            field=models.CharField(max_length=255, unique=True, verbose_name='Descricao da Função'),
        ),
    ]
