# Generated by Django 6.0.2 on 2026-03-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_colaborador_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrocusto',
            options={'ordering': ['descricao'], 'verbose_name': 'Ativo', 'verbose_name_plural': 'Ativos'},
        ),
        migrations.RemoveField(
            model_name='centrocusto',
            name='centro_pai',
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='cod_do_ativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='cod_tag',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='tag_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtags', to='cadastro.centrocusto'),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=36),
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.UniqueConstraint(condition=models.Q(('cod_tag__isnull', False)), fields=('tenant_id', 'cod_tag'), name='uniq_cod_tag_por_tenant'),
        ),
    ]
