# Generated by Django 6.0.2 on 2026-02-12 02:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("abertura_os", "0001_initial"),
        ("cadastro", "0008_alter_apontamentohoras_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApontamentoHoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                ("tipo_dia", models.CharField(blank=True, max_length=20)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apontamentos_lancamento",
                        to="cadastro.colaborador",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="abertura_os.aberturaos",
                    ),
                ),
            ],
        ),
    ]
